import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import React from 'react';
import Main from "./home/main"
export default function index() {
	return (
		<>
			<Head>
				<title>Đầu trâu tụ họp</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
				<Main></Main>
			</div>
		</>
	)
}
